# Auto-generated by scripts/gen-formula.sh on each release. Do not edit by hand.
class Mcc < Formula
  desc "Run multiple Claude Code CLI profiles on one device"
  homepage "https://github.com/husseinAbdElaziz/multi-claude"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/husseinAbdElaziz/multi-claude/releases/download/v0.1.0/mcc-macos-arm64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    else
      url "https://github.com/husseinAbdElaziz/multi-claude/releases/download/v0.1.0/mcc-macos-x64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/husseinAbdElaziz/multi-claude/releases/download/v0.1.0/mcc-linux-arm64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    else
      url "https://github.com/husseinAbdElaziz/multi-claude/releases/download/v0.1.0/mcc-linux-x64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bin.install "mcc"
  end

  def caveats
    <<~EOS
      mcc launches the Claude Code CLI, so make sure `claude` is installed and on
      your PATH: https://docs.anthropic.com/en/docs/claude-code
    EOS
  end

  test do
    assert_match "mcc #{version}", shell_output("#{bin}/mcc --version")
  end
end
