#!/usr/bin/env bash
# Generate the Homebrew formula for a release.
#
# Usage: scripts/gen-formula.sh <version> <sha256sums-file>
#
# The SHA256SUMS file is the `sha256sum` output over the release tarballs
# (one "<hash>  <filename>" line per asset). The generated formula is printed
# to stdout.
set -euo pipefail

VERSION="${1:?usage: gen-formula.sh <version> <sha256sums-file>}"
SUMS="${2:?usage: gen-formula.sh <version> <sha256sums-file>}"
VERSION="${VERSION#v}"
REPO="husseinAbdElaziz/multi-claude"
BASE="https://github.com/${REPO}/releases/download/v${VERSION}"

sha() {
  # Print the sha256 for an asset filename, or a placeholder if missing.
  local found
  found="$(awk -v f="$1" '$2 == f {print $1}' "$SUMS")"
  echo "${found:-0000000000000000000000000000000000000000000000000000000000000000}"
}

cat <<EOF
# Auto-generated by scripts/gen-formula.sh on each release. Do not edit by hand.
class Mcc < Formula
  desc "Run multiple Claude Code CLI profiles on one device"
  homepage "https://github.com/${REPO}"
  version "${VERSION}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "${BASE}/mcc-macos-arm64.tar.gz"
      sha256 "$(sha mcc-macos-arm64.tar.gz)"
    else
      url "${BASE}/mcc-macos-x64.tar.gz"
      sha256 "$(sha mcc-macos-x64.tar.gz)"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "${BASE}/mcc-linux-arm64.tar.gz"
      sha256 "$(sha mcc-linux-arm64.tar.gz)"
    else
      url "${BASE}/mcc-linux-x64.tar.gz"
      sha256 "$(sha mcc-linux-x64.tar.gz)"
    end
  end

  def install
    bin.install "mcc"
  end

  def caveats
    <<~EOS
      mcc launches the Claude Code CLI, so make sure \`claude\` is installed and on
      your PATH: https://docs.anthropic.com/en/docs/claude-code
    EOS
  end

  test do
    assert_match "mcc #{version}", shell_output("#{bin}/mcc --version")
  end
end
EOF
